language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t aleksas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aleksas/docker-react npm run test